version: '3.9'

services:
  merchant:
    build: .
    container_name: merchant_app
    ports:
      - "9091:9091"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=merchant_user
      - DB_PASSWORD=merchant_pass
      - DB_NAME=merchant_db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: merchant_db
    environment:
      POSTGRES_USER: merchant_user
      POSTGRES_PASSWORD: merchant_pass
      POSTGRES_DB: merchant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
